# Generated by Django 4.2.4 on 2023-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100, null=True)),
                ('text_field', models.TextField(null=True)),
                ('integer_field', models.IntegerField(max_length=50, null=True)),
                ('float_field', models.FloatField(max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('date_field', models.DateField(auto_now=True, null=True)),
                ('datetime_field', models.DateTimeField(auto_now=True, null=True)),
                ('decimal_field', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('email_field', models.EmailField(max_length=254, null=True)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='nameFile')),
            ],
        ),
    ]
